name: $(runTitle)_${{ parameters.environment }}_$(Build.SourceBranchName)_$(date:yyyyMMdd)$(rev:.r)

trigger: none

pool:
  vmImage: "Ubuntu-latest"

parameters:
  - name: environment
    displayName: Run environment
    type: string
    default: qa
    values:
      - qa
      - staging
  - name: hwPlatform
    displayName: Hardware platform
    type: string
    default: 'All'
    values:
      - platform_a
      - platform_b
      - All
  - name: priority
    displayName: Priority
    type: string
    default: 'All'
    values:
      - Critical
      - Normal
      - All
  - name: testId
    displayName: Test Id
    type: string
    default: '.'
  - name: reportLogLevel
    displayName: 'Html report log level'
    type: string
    default: 'Information'
    values:
      - Validation
      - Information
      - Verbose

variables:
  - template: ./templates/variables.yml
    parameters:
      environment: ${{ parameters.environment }}
      hwPlatform: ${{ parameters.hwPlatform }}
      priority: ${{ parameters.priority }}
      testId: ${{ parameters.testId }}
      reportLogLevel: ${{ parameters.reportLogLevel }}

jobs:
  - template: ./templates/jobs/run-tests.yml
    parameters:
      environment: ${{ parameters.environment }}
      testFilter: $(priorityFilter) & $(hwPlatformFilter) & $(testIdFilter)
      emailSubject: '[$(runTitle)] [{environmentStatus}] {passPercentage} tests passed in ${{ parameters.environment }} environment'
